### ISSUE TITLE
installing error using pip

### ISSUE THREAD

**Issue by marcoramosw** [up42/image-similarity-measures#16]
the following error occurs when I try to install:

ERROR: Could not find a version that satisfies the requirement image-similarity-measures (from versions: none)
ERROR: No matching distribution found for image-similarity-measures

**Comment by nekhtiari** [comment]
Dear @marcoramosw, thank you for your comment, will look into this ASAP and will let you know when we know more.

**Comment by nachogoro** [comment]
Piggybacking on this thread to comment that I found this ticket because I'm bumping into the same issue :)

**Comment by nekhtiari** [comment]
Thank you for your comment, we will look into this today and will let you know.

**Comment by zwep** [comment]
Hi,

had the same error when using `pip install ...`. Since you wrote a nice setup.sh script, I could also execute `pip install git+https://github.com/up42/image-similarity-measures.git`

Giving me a more insightful error message:
"ERROR: Package 'image-similarity-measures' requires a different Python: 3.8.0 not in '>=3.6, <3.8'"

Soo.. yeah there is it.

**Comment by nekhtiari** [comment]
@zwep thank you for your message, indeed your hint related to the python version is correct. Now we are making sure that the package can be installed with python 3.8 as well. PR is out and the new version will be deployed ASAP.

**Comment by nekhtiari** [comment]
@nachogoro and @marcoramosw the new version of the package has been deployed. feel free to try it out. For the time being, I will close this issue. If you find any problem with the installation again feel free to reopen this one again.

**Comment by marcoramosw** [comment]
thank you

**Comment by nachogoro** [comment]
Thanks for the quick fix!
