### ISSUE TITLE
is the RMSE wrong?

### ISSUE THREAD

**Issue by lxc-love-zy** [up42/image-similarity-measures#31]
I checked the RMSE computing process and it returns a mean, but it should be np.sqrt at last.

**Comment by nikooc2s** [comment]
Hey at line 37 we are doing the sqrt. The last mean you see is the mean for all bands.

**Comment by nikooc2s** [comment]
@chrieke can you close this? Unfortunately, I can't ....

**Comment by Safiullahmarwat** [comment]
I think RMSE is wrong. `i` is not used inside the `for` loop, which means that same operations are performed thrice. if you `print(s)` inside the `for` loop, the results is same for each channel. 
I further checked with the RMSE equation `np.sqrt(((img1- img2) ** 2).mean())` and `sklearn.metrics.mean_squared_error` and found that these results are different than `rmse` of this package.

**Comment by nekhtiari** [comment]
Oh that is true, since [here](https://github.com/up42/image-similarity-measures/commit/101e4764b15c31238e00d04efd21173a86c97a3d) we still had the `i` in the calculation. Not sure what removed it. Will make a PR. Thanks for the catch.

**Comment by chrieke** [comment]
Fixed in https://github.com/up42/image-similarity-measures/pull/37
