### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by uly94** [up42/image-similarity-measures#33]
Hi all, I've downloaded .zip project and then I imported it as a PyCharm project. If I try to execute the command with correct params and any type of command console returns me this error -->
![image](https://user-images.githubusercontent.com/18552295/136537441-52a33da1-f7ac-48e3-8bb2-654f4dc9e999.png)
![image](https://user-images.githubusercontent.com/18552295/136537555-70bab2d9-d506-4dbc-a0a2-fbaf412d2c86.png)
I tried to install FFTW libraries but I got the same error

How can I install this great package without any error? Thanks in advance

**Comment by chrieke** [comment]
Hi @uly94 you can install the package via the pip package manager, no need to download the zip file.

Please follow the installation instructions: https://github.com/up42/image-similarity-measures#install-package

**Comment by uly94** [comment]
OK, thank you. Package has many errors but you can solve them spending some time.

**Comment by nikooc2s** [comment]
> OK, thank you. Package has many errors but you can solve them spending some time.

Hey, please feel free to add your corrections in the code. We would highly appreciate this.
