### ISSUE TITLE
Support python 3.10

### ISSUE THREAD

**Issue by baterflyrity** [up42/image-similarity-measures#38]
Hi! Im developing my own image format hence i need this package for lossy compression quality evaluation. Can you please update this package for python 3.10 usage. Thanks.

p.s.
All dependencies support python 3.10 so now i just copied quality_metrics.py into my project.

**Comment by nekhtiari** [comment]
@baterflyrity Sure, will check this :)

**Comment by akx** [comment]
This would be fixed by #42 and #43.

**Comment by chrieke** [comment]
upper Python version bounds removed in https://github.com/up42/image-similarity-measures/pull/42
