### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by livan3li** [up42/image-similarity-measures#39]
Hi, first of all thank you for sharing such a great tool. 

i've tried to install by using pip but i got following error. Could you help?

PS E:\MyAllProjects\Python\BoundingBox> pip install image-similarity-measures
Collecting image-similarity-measures
  Using cached image_similarity_measures-0.3.5-py3-none-any.whl (9.1 kB)
Requirement already satisfied: numpy in e:\myallprojects\python\boundingbox\dataprep\lib\site-packages (from image-similarity-measures) (1.22.3)
Collecting rasterio
  Using cached rasterio-1.2.10.tar.gz (2.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
      ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by chrieke** [comment]
Hi @livan3li looks very much like a typical rasterio/gdal installation issue on Windows. Would recommend that you manually install the rasterio wheels before installing the package.

Download the [rasterio wheels](https://www.lfd.uci.edu/~gohlke/pythonlibs/#rasterio) here (apprioiate to your Windows version), open the terminal, `cd` to the directory with the downloaded file, and do `pip install filename-of-rasterio-wheels`. Then try again the image similarity installation.

**Comment by livan3li** [comment]
thank you a lot for helping. How can i know my system supports which version?. 

I'm using Windows 10 Version: 21H2 OS Build: 19044.1706

**Comment by livan3li** [comment]
@chrieke  i've tried bunch of different versions from the link you gave but none of them worked. 

it's also written in that in link that gdal is required and i've tried to install it as well and it didnt work neither

**Comment by Theo-Stats** [comment]
Go to https://www.lfd.uci.edu/~gohlke/pythonlibs/ and down "rasterio‑1.0.24+gdal24‑cp37‑cp37m‑win_amd64.whl" with  the corresponding version of your os
