### ISSUE TITLE
no write

### ISSUE THREAD

**Issue by jaimebayes** [up42/image-similarity-measures#7]
Hi, 

I am wondering how to avoid it saves the result into a file.
I have try different values but it keeps saving files

--write_to_file='FALSE'
--write_to_file=FALSE
--write_to_file=False

Could you indicate me what is the right parameter value?

Thanks in advance, JL

**Comment by nekhtiari** [comment]
Hey JL,

Thank you for your comment. Fix in on the way for this.

**Comment by nekhtiari** [comment]
So now if you try again without adding --write_to_file, no folder will be created. In a case you want to have it you can just add --write_to_file at the end of the command. Let me know if it works for you.

**Comment by jaimebayes** [comment]
Great!, it works now,
Thanks @nekhtiari
